version: '3.8'

services:
  backend:
    build: .
    container_name: flashspace-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_URI=mongodb://mongo:27017/myapp # Connect to mongo container
    env_file:
      - .env
    volumes:
      - ./src/flashspaceWeb/meetingSchedulerModule/google-tokens.json:/app/dist/flashspaceWeb/meetingSchedulerModule/google-tokens.json
    depends_on:
      - redis
      - mongo
    networks:
      - flashspace-network

  redis:
    image: redis:alpine
    container_name: flashspace-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - flashspace-network

  mongo:
    image: mongo:latest
    container_name: flashspace-mongo
    restart: always
    ports:
      - "27018:27017" # Expose to host on 27018 to avoid conflict with local DB
    volumes:
      - mongo-data:/data/db # Persist data
    networks:
      - flashspace-network

networks:
  flashspace-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local